source 'https://rubygems.org'

gem 'foreman'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-rocketio'
gem 'eventmachine'
gem 'event_emitter'
gem 'json'
gem 'haml'
gem 'sass'
gem 'tiqav'
gem 'dalli'
gem 'rmagick'
gem 'gruff'

# brew install imagemagick
# brew install gs

#gem 'erb'
